version: '3.6'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGODB_USER: root
      MONGODB_PASS: supersafe
      MONGODB_DATABASE: urlshortener
    ports:
     - "12345:27017"
